version: '3.2'

services:

  greeter_test:
    build:
      context: .
    image: greeter
    command: python -m unittest discover -v
    networks:
      - lab_network
    profiles:
      - donotstart

networks:
  lab_network:
    external: false
